# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_logic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='result',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='type',
            field=models.CharField(default='D2H', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='value',
            field=models.CharField(default='8191', max_length=100),
        ),
    ]
