# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_logic_app', '0002_auto_20180515_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(default='encoding', max_length=100)),
                ('input', models.CharField(default='8191', max_length=100)),
                ('result', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
